/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CentersRouteImport } from './routes/centers'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CentersSlugRouteImport } from './routes/centers.$slug'
import { Route as CenterSubscriptionRouteImport } from './routes/center.subscription'
import { Route as CenterServicesRouteImport } from './routes/center.services'
import { Route as CenterProfileRouteImport } from './routes/center.profile'
import { Route as CenterOnboardingRouteImport } from './routes/center.onboarding'
import { Route as CenterDashboardRouteImport } from './routes/center.dashboard'
import { Route as CenterBookingsRouteImport } from './routes/center.bookings'
import { Route as BookServiceIdRouteImport } from './routes/book.$serviceId'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AdminSystemRouteImport } from './routes/admin.system'
import { Route as AdminSubscriptionsRouteImport } from './routes/admin.subscriptions'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminCommissionsRouteImport } from './routes/admin.commissions'
import { Route as AdminCentersRouteImport } from './routes/admin.centers'
import { Route as AdminBookingsRouteImport } from './routes/admin.bookings'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CentersRoute = CentersRouteImport.update({
  id: '/centers',
  path: '/centers',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CentersSlugRoute = CentersSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CentersRoute,
} as any)
const CenterSubscriptionRoute = CenterSubscriptionRouteImport.update({
  id: '/center/subscription',
  path: '/center/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const CenterServicesRoute = CenterServicesRouteImport.update({
  id: '/center/services',
  path: '/center/services',
  getParentRoute: () => rootRouteImport,
} as any)
const CenterProfileRoute = CenterProfileRouteImport.update({
  id: '/center/profile',
  path: '/center/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const CenterOnboardingRoute = CenterOnboardingRouteImport.update({
  id: '/center/onboarding',
  path: '/center/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const CenterDashboardRoute = CenterDashboardRouteImport.update({
  id: '/center/dashboard',
  path: '/center/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CenterBookingsRoute = CenterBookingsRouteImport.update({
  id: '/center/bookings',
  path: '/center/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const BookServiceIdRoute = BookServiceIdRouteImport.update({
  id: '/book/$serviceId',
  path: '/book/$serviceId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSystemRoute = AdminSystemRouteImport.update({
  id: '/admin/system',
  path: '/admin/system',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: '/admin/subscriptions',
  path: '/admin/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCommissionsRoute = AdminCommissionsRouteImport.update({
  id: '/admin/commissions',
  path: '/admin/commissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCentersRoute = AdminCentersRouteImport.update({
  id: '/admin/centers',
  path: '/admin/centers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/admin/bookings',
  path: '/admin/bookings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/centers': typeof CentersRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/centers': typeof AdminCentersRoute
  '/admin/commissions': typeof AdminCommissionsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/system': typeof AdminSystemRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/book/$serviceId': typeof BookServiceIdRoute
  '/center/bookings': typeof CenterBookingsRoute
  '/center/dashboard': typeof CenterDashboardRoute
  '/center/onboarding': typeof CenterOnboardingRoute
  '/center/profile': typeof CenterProfileRoute
  '/center/services': typeof CenterServicesRoute
  '/center/subscription': typeof CenterSubscriptionRoute
  '/centers/$slug': typeof CentersSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/centers': typeof CentersRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/centers': typeof AdminCentersRoute
  '/admin/commissions': typeof AdminCommissionsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/system': typeof AdminSystemRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/book/$serviceId': typeof BookServiceIdRoute
  '/center/bookings': typeof CenterBookingsRoute
  '/center/dashboard': typeof CenterDashboardRoute
  '/center/onboarding': typeof CenterOnboardingRoute
  '/center/profile': typeof CenterProfileRoute
  '/center/services': typeof CenterServicesRoute
  '/center/subscription': typeof CenterSubscriptionRoute
  '/centers/$slug': typeof CentersSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/centers': typeof CentersRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/centers': typeof AdminCentersRoute
  '/admin/commissions': typeof AdminCommissionsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/system': typeof AdminSystemRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/book/$serviceId': typeof BookServiceIdRoute
  '/center/bookings': typeof CenterBookingsRoute
  '/center/dashboard': typeof CenterDashboardRoute
  '/center/onboarding': typeof CenterOnboardingRoute
  '/center/profile': typeof CenterProfileRoute
  '/center/services': typeof CenterServicesRoute
  '/center/subscription': typeof CenterSubscriptionRoute
  '/centers/$slug': typeof CentersSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/centers'
    | '/dashboard'
    | '/admin/bookings'
    | '/admin/centers'
    | '/admin/commissions'
    | '/admin/dashboard'
    | '/admin/subscriptions'
    | '/admin/system'
    | '/auth/login'
    | '/auth/signup'
    | '/book/$serviceId'
    | '/center/bookings'
    | '/center/dashboard'
    | '/center/onboarding'
    | '/center/profile'
    | '/center/services'
    | '/center/subscription'
    | '/centers/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/centers'
    | '/dashboard'
    | '/admin/bookings'
    | '/admin/centers'
    | '/admin/commissions'
    | '/admin/dashboard'
    | '/admin/subscriptions'
    | '/admin/system'
    | '/auth/login'
    | '/auth/signup'
    | '/book/$serviceId'
    | '/center/bookings'
    | '/center/dashboard'
    | '/center/onboarding'
    | '/center/profile'
    | '/center/services'
    | '/center/subscription'
    | '/centers/$slug'
  id:
    | '__root__'
    | '/'
    | '/centers'
    | '/dashboard'
    | '/admin/bookings'
    | '/admin/centers'
    | '/admin/commissions'
    | '/admin/dashboard'
    | '/admin/subscriptions'
    | '/admin/system'
    | '/auth/login'
    | '/auth/signup'
    | '/book/$serviceId'
    | '/center/bookings'
    | '/center/dashboard'
    | '/center/onboarding'
    | '/center/profile'
    | '/center/services'
    | '/center/subscription'
    | '/centers/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CentersRoute: typeof CentersRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminCentersRoute: typeof AdminCentersRoute
  AdminCommissionsRoute: typeof AdminCommissionsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRoute
  AdminSystemRoute: typeof AdminSystemRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  BookServiceIdRoute: typeof BookServiceIdRoute
  CenterBookingsRoute: typeof CenterBookingsRoute
  CenterDashboardRoute: typeof CenterDashboardRoute
  CenterOnboardingRoute: typeof CenterOnboardingRoute
  CenterProfileRoute: typeof CenterProfileRoute
  CenterServicesRoute: typeof CenterServicesRoute
  CenterSubscriptionRoute: typeof CenterSubscriptionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/centers': {
      id: '/centers'
      path: '/centers'
      fullPath: '/centers'
      preLoaderRoute: typeof CentersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/centers/$slug': {
      id: '/centers/$slug'
      path: '/$slug'
      fullPath: '/centers/$slug'
      preLoaderRoute: typeof CentersSlugRouteImport
      parentRoute: typeof CentersRoute
    }
    '/center/subscription': {
      id: '/center/subscription'
      path: '/center/subscription'
      fullPath: '/center/subscription'
      preLoaderRoute: typeof CenterSubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/center/services': {
      id: '/center/services'
      path: '/center/services'
      fullPath: '/center/services'
      preLoaderRoute: typeof CenterServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/center/profile': {
      id: '/center/profile'
      path: '/center/profile'
      fullPath: '/center/profile'
      preLoaderRoute: typeof CenterProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/center/onboarding': {
      id: '/center/onboarding'
      path: '/center/onboarding'
      fullPath: '/center/onboarding'
      preLoaderRoute: typeof CenterOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/center/dashboard': {
      id: '/center/dashboard'
      path: '/center/dashboard'
      fullPath: '/center/dashboard'
      preLoaderRoute: typeof CenterDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/center/bookings': {
      id: '/center/bookings'
      path: '/center/bookings'
      fullPath: '/center/bookings'
      preLoaderRoute: typeof CenterBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$serviceId': {
      id: '/book/$serviceId'
      path: '/book/$serviceId'
      fullPath: '/book/$serviceId'
      preLoaderRoute: typeof BookServiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/system': {
      id: '/admin/system'
      path: '/admin/system'
      fullPath: '/admin/system'
      preLoaderRoute: typeof AdminSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/subscriptions': {
      id: '/admin/subscriptions'
      path: '/admin/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/commissions': {
      id: '/admin/commissions'
      path: '/admin/commissions'
      fullPath: '/admin/commissions'
      preLoaderRoute: typeof AdminCommissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/centers': {
      id: '/admin/centers'
      path: '/admin/centers'
      fullPath: '/admin/centers'
      preLoaderRoute: typeof AdminCentersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/admin/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CentersRouteChildren {
  CentersSlugRoute: typeof CentersSlugRoute
}

const CentersRouteChildren: CentersRouteChildren = {
  CentersSlugRoute: CentersSlugRoute,
}

const CentersRouteWithChildren =
  CentersRoute._addFileChildren(CentersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CentersRoute: CentersRouteWithChildren,
  DashboardRoute: DashboardRoute,
  AdminBookingsRoute: AdminBookingsRoute,
  AdminCentersRoute: AdminCentersRoute,
  AdminCommissionsRoute: AdminCommissionsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminSubscriptionsRoute: AdminSubscriptionsRoute,
  AdminSystemRoute: AdminSystemRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  BookServiceIdRoute: BookServiceIdRoute,
  CenterBookingsRoute: CenterBookingsRoute,
  CenterDashboardRoute: CenterDashboardRoute,
  CenterOnboardingRoute: CenterOnboardingRoute,
  CenterProfileRoute: CenterProfileRoute,
  CenterServicesRoute: CenterServicesRoute,
  CenterSubscriptionRoute: CenterSubscriptionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
